### ISSUE TITLE
negative temperature values calculation incorrect

### ISSUE THREAD

**Issue by gerthmar** [RobTillaart/MCP9808_RT#7]
Hi, thanks for your great library!

I had an issue with negative temperatures and going throug the device's datasheet, I think the 

`return 256 - (val & 0x0FFF) * 0.0625;` (line 217 mcp9808.cpp)

should be

`return (256.0 - (val & 0x0FFF) * 0.0625) * -1.0;` (line 217 mcp9808.cpp)

With the multiplication by -1, the values make sense in my application.

**Comment by RobTillaart** [comment]
@gerthmar 

Not tested with negative temperatures I assume. I will look into it right away.

**Comment by RobTillaart** [comment]
from the datasheet ...
![image](https://user-images.githubusercontent.com/462844/142664366-99311259-6a7f-4e3b-b5e6-919542ee352f.png)

**Comment by gerthmar** [comment]
I think the datasheet is a bit misleading. The equation gives the temperature without the sign. So if the temperature is -10°C, the formular will give 10. The sign has to be 'added' to get the float value.

**Comment by RobTillaart** [comment]
Can you verify if the following line works.  (multiplication less)

```return (val & 0x0FFF) * 0.0625) - 256;```

**Comment by gerthmar** [comment]
I cooled the sensor down  with a freezer spray and then let it warm up the ambient temperature. The value make sense.

![grafik](https://user-images.githubusercontent.com/6299676/142665946-13782ecb-ee79-4f94-b4a6-c13db7ed16b4.png)

**Comment by RobTillaart** [comment]
(just had dinner)
Cool such spray, I am always taking my setup to the freezer and put the sensor between the frozen veggies.
Think this such spray is easier, is it environmentally safe?

**Comment by RobTillaart** [comment]
Merged the PR.
If there are other issues, let me know.

**Comment by gerthmar** [comment]
> (just had dinner) Cool such spray, I am always taking my setup to the freezer and put the sensor between the frozen veggies. Think this such spray is easier, is it environmentally safe?

Thats the advantage of working in an electronics lab :-) I am not aware of any negative environment impact...

Thanks a lot for the merge!
